### ISSUE TITLE
Firmware compiles and uploads but then does nothing

### ISSUE THREAD

**Issue by chron0** [andrewsil1/FelixMarlin#1]
Hi there. Thank you very much for maintaining and releasing a Marlin branch for Felix. Recently we've updated our Felix to 3.0 (https://apollo.open-resource.org/mission:resources:picoprint) and with that process I wanted to have a closer look on firmwares, especially Marlin vs. Repetier. 

I've managed to verify/compile and upload this branch to the Controller but once it resets, the second led (which blinks fast during the flashing process) is only showing blink - blink - 2 sec pause - blink - blink and so on. Then I've tried ANY Marlin based firmware and they all show the same behavior. From the host (octoprint), there is no communication possible to the board.

However, when I compile and upload one of the repetier branches from the felix download site it works but I had to go back to 0.91 (Jan 2014) since everything more recent never survived prints longer than 1 hour due to some noise issues letting the bot think it had a decoupled temperature sensor :/

We can work with the 0.91 repetier FW now but it would be nice to have open/free alternatives and compare results and then head over to dual extruder operation.

So, is there any trick or something else that needs to be done to work with Marlin/Octoprint? Baudrate is 250000 to reduce clock/sync issues. I'd like to test this FW's PID implementation for the bed (although we did insulate our bed to reduce thermal waste and warping/expansion issues). Any help would be appreciated :)

**Comment by andrewsil1** [comment]
Well, to be honest I've never tried to use Octoprint, but clearly it's supposed to work with Marlin, it runs far more printers in the real world than Repetier firmware.

Have you tried using RepetierHost or some other app to first verify that the printer simply works at all under Marlin?  To be honest, I would suspect an Octoprint configuration or setup issue assuming the printer works normally with other applications.

_____________
Andy




On Mon, Feb 23, 2015 at 2:51 AM -0800, "chrono" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there. Thank you very much for maintaining and releasing a Marlin branch for Felix. Recently we've updated our Felix to 3.0 (https://apollo.open-resource.org/mission:resources:picoprint) and with that process I wanted to have a closer look on firmwares, especially Marlin vs. Repetier.

I've managed to verify/compile and upload this branch to the Controller but once it resets, the second led (which blinks fast during the flashing process) is only showing blink - blink - 2 sec pause - blink - blink and so on. Then I've tried ANY Marlin based firmware and they all show the same behavior. From the host (octoprint), there is no communication possible to the board.

However, when I compile and upload one of the repetier branches from the felix download site it works but I had to go back to 0.91 (Jan 2014) since everything more recent never survived prints longer than 1 hour due to some noise issues letting the bot think it had a decoupled temperature sensor :/

We can work with the 0.91 repetier FW now but it would be nice to have open/free alternatives and compare results and then head over to dual extruder operation.

So, is there any trick or something else that needs to be done to work with Marlin/Octoprint? Baudrate is 250000 to reduce clock/sync issues. I'd like to test this FW's PID implementation for the bed (although we did insulate our bed to reduce thermal waste and warping/expansion issues). Any help would be appreciated :)

-

**Comment by chron0** [comment]
Hmm, I'll try to play with the start/wait timeouts of octoprint (https://groups.google.com/forum/#!msg/octoprint/qQ8EEg_wInA/Z6ELp7WYRhEJ) since this Marlin branch and the "official" felix upstream Marlin branch show the exact same behavior, so I don't think there is an issue with your code. I was just hoping that I've missed something obvious to get the tests going :)

**Comment by chron0** [comment]
So, time to close this one :) I couldn't get Octoprint to connect to this branch at all, no matter which timeouts I tried. After using vanilla Marlin it worked directly, I just had to change a bit of the configuration. Now we have another fork of Marlin for the Felix which I think i kinda ridiculous so I'd like to invite you to have a look into https://github.com/MarlinFirmware/Marlin/pull/1546 so that we can pool our efforts to have direct upstream support for the Felix in Marlin. This is just a first step and basic printing is working, I can't test LCD/SD but I've got a dual head. So depending on the state of your Felix we could combine our efforts to get everything supported and tested by mashing our code/configs.

My next steps:

BEDPID (currently disabled)
DUAL Head support

**Comment by andrewsil1** [comment]
I think the better route of the two is clearly to include working sample configs for Felix upstream so that it's just natively supported.  My own fork was really just meant as a stopgap, since prior to all this recent activity in the main Marlin branch there were very few sample configs at all, so it seemed a little odd to have one just for Marlin.  I haven't been keeping the fork up to date for the last few weeks because, frankly, what they had going on seemed just too unstable with huge amounts of churn.  But I'm sure that eventually it will settle down and things will get cleaned up, and then there won't be any need for this fork anymore.  In fact, I wouldn't be at all surprised to find that Octoprint now works due to a recent change or fix to the main branch, as there was nothing in particular about my fork that was different in any code sense that wouldn't have also happened using the main branch of the time, my only local edits were to the config.

**Comment by chron0** [comment]
Fully agree. And thanks again a thousand times for taking the time and sharing your results on github, even though I couldn't get it to work, it was a tremendous help to be able to look at your configuration parameters to have a somewhat independent source of data of someone who probably has a felix printer and would see if the parameters are completely off. In the end I just took your parameters, compared them against the original felix configuration parameters and mashed that up with the current marlin configuration scheme. I'm also not sure if there wasn't an even nastier bug why I couldn't get it to work: I know that some when in between experiments I switched the USB cable which might have something do with it, I realized afterwards. But by looking at your work I was able to bootstrap my mashup very fast and could produce something we can hopefully merge and extend upstream now.
